language: node_js

node_js: 
  - 11.6.0

cache: npm

install: 
  - npm install

branches:
only:
  - test-ci

script: 
  - docker pull leonardorsilveira/nginx-atp02:latest
  - docker run -p 8085:80 -v $(pwd)/html:/usr/share/nginx/html nginx

after_script:
  - bash ./telegram_notification.sh

after_success:

  - ls  
  - chmod +x final_report.sh
  - . final_report.sh
  
  - git init
  - git config user.name "Travis CI"
  - git config user.email "travis@travis.org"
  - git add cucumber_report.html
  - git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GITHUB_API_KEY}@${GH_REF}" main:gh-pages
  - echo $RESULT
  - bash ./telegram_notification.sh
